### ISSUE TITLE
Envío de catálogo

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#11]
Terminar de resolver cual es el proceso de envío de catalogo a amigos. Si va a ser con uno o dos botones. Si va a ser a amigos nuevos o a amigos que esten usando addfow. Necesitamos simplificar al maximo esta acción para que tenga la menor fricción posible con el usuario.

**Comment by paveliz** [comment]
El proceso como está hoy es como FB también nos deja hacerlo:

- Hay 2 botones, uno para invitar usuarios y agregarlos al listado y el otro boton para enviar el catálogo a los usuarios ya existentes.

- De todas formas, los dos botones cumplen la función de recomendar el catálogo seleccionado. Lo hicimos así para que no se pierda el circuito de venta y no quede tan mal.

- El mensaje que se envía es FIJO. No se puede customizar por usuario o por catálogo.

- Se puede seleccionar un usuario del listado, pero solo deja hasta un usuario. Más usuarios hay que agregarlos a mano.

Y como se comentó antes, según lo que leímos, estas son las restricciones por ser una app web fuera del contenedor de FB. Hay que probar colocando la app en facebook y muy posiblemente se pueda mejorar el circuito.

**Comment by romafederico** [comment]
Ok. Esperamos a que la app de facebook.
