### ISSUE TITLE
Usuario duplicado

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#14]
En el BO estoy viendo dos usuarios con el mismo mail: pikigm@gmail.com. Uno tiene perfil de revendedora y otro de invitado... ¿Por que?

**Comment by romafederico** [comment]
No recuerdo si habian respondido sobre este punto.

**Comment by paveliz** [comment]
El comentario fué que no pudimos reproducir el caso, pero pudo haber pasado por no haber puesto algunas validaciones. Así que hicimos algunas modificaciones en el BO para quedarnos tranquilos.
