### ISSUE TITLE
Tipos de usuario

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#17]
Si un usuario revendendedor envia un catalogo a otro revendedor y este lo abre, el segundo revendedor cambia su estado en BO a cliente.

**Comment by paveliz** [comment]
Solo para aclarar algo..., siguiendo el ejemplo que vos contas..., en el BO vas a ver:

- Si ingresas al usuario A (revendedor), vas a ver al usuario B como cliente. B recibió el catálogo de A y por ende es cliente de A.

- En el listado general, también vas a ver al usuario B pero como revendedor. Cuando ingreses al mismo, vas a ver todos sus clientes.

Un usuario no tiene un único estado..., es "cliente" en algunos casos y "revendedor" en otros.

Confirmame si estamos alineados.

**Comment by romafederico** [comment]
El tema es que si el usuario B era revendedor, recibió un catalogo y paso a ser cliente, todas las opciones de revendedor le desaparecen del FO.

**Comment by paveliz** [comment]
Ok, ahora si. Pero eso es un error en el FO no el BO, el bug parece que el error es el BO.

Ok, entonces, revisamos que no se le cambien las opciones al usuario.
