### ISSUE TITLE
Login con FB

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#18]
Si recibo un catalogo en FB y ya tengo una cuenta de Addfow, el usuario debe ir directamente sobre la primera pagina del catalogo y no tener que pasar por la landing de login y los coachmarks.

**Comment by paveliz** [comment]
Se puede hacer siempre y cuando no se haya perdido el login o sesión de FB. En tal caso, el sistema necesita pedirle el login al usuario.

**Comment by romafederico** [comment]
OK!

**Comment by romafederico** [comment]
Cuando recibo un catalogo y hago click en el link, me lleva a la home de Addfow donde me deberia loguear con facebook, y pasados unos segundos me loguea automaticamente. 

No deberiamos ver la landing y a los pocos segundos loguear al usuario. Deberiamos loguearlo directamente.

**Comment by paveliz** [comment]
Fede, esto es por el login de Facebook, no es algo nuestro. Procesa el login de facebook e ingresa a la url.
