### ISSUE TITLE
Coachmarks

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#2]
1. Deberían estar maquetados sobre la pantalla real, no ser una captura de la imagen y ser responsive. 
2. Deberían verse solo la primera vez que ingreso a la plataforma, no cada vez que se ingresa a la plataforma.

![image](https://cloud.githubusercontent.com/assets/3988119/7446925/fb196eae-f1be-11e4-934d-f0436569bea8.png)

**Comment by paveliz** [comment]
Fede, hay que se parar en dos este ticket porque son dos cosas diferentes. El primero punto es complicado, deberíamos haber hablado mucho antes de esto, separalo en otro ticket y lo vemos.

El segundo punto dejalo en este ticket si queres.

**Comment by romafederico** [comment]
Borre un usuario del CMS, ingrese nuevamente con Facebook y no mostro los coachmarks.

**Comment by paveliz** [comment]
Proba nuevamente Fede, borrando el usuario desde el BO e ingresando.

**Comment by romafederico** [comment]
Te digo los pasos que hice:
1. Sali de la app
2. Borre mi usuario desde el BO
3. Ingrese en una ventana de incognito al front
4. Hice click en el boton de facebook
5. ingrese mis credenciales de facebook
6. Aterrice en el listado de catalogos
7. Nunca vi los coachmarks.

Para los usuarios que ingresan por primera vez los coachmarks deberian mostrarse siempre.
