### ISSUE TITLE
Tamaños de página

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#22]
Revisar que pasa con el visor de catalogos cuando:

1. Se sube una imagen que es mas alta que ancha
2. Se suben distintos tamaños de imagen

![screenshot 2015-05-03 at 19 20 16](https://cloud.githubusercontent.com/assets/3988119/7447241/8e2bd434-f1c9-11e4-8936-b53627a3d23f.png)

**Comment by romafederico** [comment]
Si subo una imagen mas alta que ancha se corta la imagen. Deberiamos mostrarla:
- La altura debe ser la misma que para las imagenes apaisadas.
- Centrada con respecto a los botones de anterior y siguiente

**Comment by paveliz** [comment]
Fede, definí por favor mejor la funcionalidad que estas buscando. El catálogo se crea desde el BO, habíamos hablamos que se entendía que la gente que va a subir las imágenes en el BO va a respetar los tamaños que se requieran. Si no es así, lo que se puede hacer es que desde el BO se procesen las imágenes para que corten y encuadren en el catálogo. El procesamiento se tiene que hacer antes..., no en el viewer, el viewer es solo eso..., sino, no es performante que corte o haga resize de la imágen.

Esto te lo comento como ayuda al ticket que estas creando, pero la verdad, no estas definiendo bien cuál es el comportamiento deseado..., si la imagen es mas grande que el viewer que tenes el front...¿que hago? ¿la recorto? ¿la deformo?

Como puse antes, el problema es funcional y para mi está en el BO no el FO. Sugiero cerrar este ticket y revisar el tema.

**Comment by romafederico** [comment]
Cierro este issue. Vamos a usar siempre el mismo tamaño de imagen.
