### ISSUE TITLE
Usuario sin mail

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#28]
El usuario Maria Lopez no tiene email asignado. Es por que fue creado por BO o por que hubo error en el login de FB?

**Comment by paveliz** [comment]
El mail es obligatorio tanto por BO como si el usuario se crea por FB. Es un usuario que crearon ustedes? yo no lo generé, puedo haber sido el Developer.

**Comment by romafederico** [comment]
Nosotros no hicimos ese usuario. Si no me equivoco, aparece en un detalle de pedido en #25 que puse una captura.
