### ISSUE TITLE
Envio de catalogo e invitaciones

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#29]
Cuando invitas amigos de facebook o mandas catalogos deberiamos tener textos predeterminados. "¡Hola! Quiero invitarte a que mires el nuevo catalogo de ,,,, "

**Comment by paveliz** [comment]
En el diálogo de Facebook, hay que ver si se puede meter un texto predeterminado. Cuando hagamos el invite que yo quiero quede implementado, ese sí 100% va a tener un mensaje predeterminado. Pero dejame verlo y confirmamos.

**Comment by paveliz** [comment]
Los mensajes pueden ser FIJOS, no dinámicos.
