### ISSUE TITLE
Coachmark 1

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#3]
Los botons de anterior y siguiente de el catalogo se confunden con anterior y siguiente de los coachmarks.

**Comment by romafederico** [comment]
No pude testearlo, no veo los coachmarks con usuarios nuevos.

**Comment by paveliz** [comment]
Fede, los coachmark aparecen solo la primera vez, había un ticket que pedía eso. Por eso para los usuarios existentes no los vas a poder ver. Pero para poder testearlo, logueate y pegale a la URL:

http://ec2-52-0-79-115.compute-1.amazonaws.com/#/coachmark

(#/coachmark) como parámetro, para poder ver el coachmark.

Igual lo que escribiste en el ticket #2 es raro..., lo revisamos y te lo contesto por ese ticket.
