### ISSUE TITLE
Sombra de popup

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#46]
En CH, FF e IE no cubre la totalidad de la pagina

![image](https://cloud.githubusercontent.com/assets/3988119/8025624/c4c3f132-0d32-11e5-9683-b1a2cdc99316.png)

**Comment by paveliz** [comment]
Fede, consulta..., esto es con alguna resolución o monitor en particular? porque no pudimos reproducirlo.

**Comment by romafederico** [comment]
Ahora no esta sucediendo. Cierro!
