### ISSUE TITLE
Pinch y Zoom

### ISSUE THREAD

**Issue by romafederico** [romafederico/addfow#61]
Estan desactivados estos gestos en mobile? Creemos que puede ser util para poder acercarse al catalogo y pedir un producto.

**Comment by pperez8279** [comment]
En general se observa buen funcionamiento del zoom.
a) En cuanto a las ventanas que se despliegan (ejemplo cuando se agrega un producto al carrito de pedidos), se observan exageradamente grande y hay moverse para abajo para poder encontrarla.
b) La función de envío de catálogos o invitación no funciona.
